CHANGELOG.md, README.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/values.yaml
The last merge into main was for v1.3.0-RC2. This PR contains the delta up to v1.3.0-RC3.
All changes can be found in the changelog
=> feat: merge upstream v1.3.0-RC3

.github/workflows/portal-chart-test.yaml, CHANGELOG.md, CODE_OF_CONDUCT.md, README.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/templates/cronjob-backend-processes.yaml, charts/portal/templates/secret-backend-interfaces.yaml, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-preprod.yaml, consortia/environments/values-beta.yaml, consortia/environments/values-dev.yaml, consortia/environments/values-int.yaml, consortia/environments/values-pen.yaml, consortia/environments/values-preprod.yaml, consortia/environments/values-rc.yaml
merge release branch in main for 1.5.0-RC1 version.
to wrap up release process main for 1.5.0-RC1 version.
n/a
=> release(1.5.0-RC1): merge release in main

consortia/environments/values-beta.yaml, consortia/environments/values-dev.yaml, consortia/environments/values-int.yaml, consortia/environments/values-pen.yaml, consortia/environments/values-rc.yaml, consortia/environments/values-stable.yaml
remove resource limits for consortia environments
change was triggered by OOMKill of the appmarketplace service on dev env
n/a
=> fix(consortia-envs): remove limits for resources

CHANGELOG.md, README.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-preprod.yaml
merge release branch in main for 1.5.0 version.
to wrap up release process for 1.5.0 version.
n/a
=>  release(1.5.0): merge release in main

CHANGELOG.md, README.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml
Updated the portal images to v1.5.1
A hotfix was made in the backend repository
N/A - Jira Issue: CPLP-2903
=> hotfix: update portal to v1.5.1

CHANGELOG.md, README.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml
merge release branch in main for 1.5.1 version.
to wrap up release process for 1.5.1 version.
n/a
=> hotfix(1.5.1): merge release in main

charts/portal/values.yaml
Description
merge current state of dev into main branch
Why
to install main branch from integration cluster and enable integration tests
Issue
Maintenance service update
https://github.com/eclipse-tractusx/portal-backend/pull/115
Checklist
=> Add new image for maintenance service

charts/portal/values.yaml, consortia/environments/values-beta.yaml, consortia/environments/values-dev.yaml, consortia/environments/values-int.yaml, consortia/environments/values-pen.yaml, consortia/environments/values-rc.yaml, consortia/environments/values-stable.yaml
merge current state of  dev into main branch
to install main branch von integration cluster and enable integration tests
https://github.com/eclipse-tractusx/portal-backend/pull/116
https://github.com/eclipse-tractusx/portal-frontend/pull/109
=> chore: merge dev in main

CHANGELOG.md, README.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/templates/deployment-backend-administration.yaml, charts/portal/templates/deployment-backend-appmarketplace.yaml, charts/portal/templates/deployment-backend-registration.yaml, charts/portal/templates/deployment-backend-services.yaml, charts/portal/values.yaml
Merge changes of 1.6.0-RC1 to main
To have the latest changes available in the main branch.
N/A
=> release(1.6.0-RC1): merge release into main

README.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/environments/values-rc.yaml
Release rc2 to main
To have the latest changes in main
N/A
=> release(1.6.0-RC2): merge release -> main

consortia/environments/values-beta.yaml, consortia/environments/values-dev.yaml, consortia/environments/values-int.yaml, consortia/environments/values-pen.yaml, consortia/environments/values-rc.yaml, consortia/environments/values-stable.yaml
Fix the offerProvider configuration
Currently the clientId of the offerProvider isn't set correctly
N/A - Jira Ticket: CPLP-3012
=> fix(offerProvider): fix offerProvider config values

CHANGELOG.md, README.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/environments/values-beta.yaml, consortia/environments/values-dev.yaml, consortia/environments/values-int.yaml, consortia/environments/values-pen.yaml, consortia/environments/values-rc.yaml, consortia/environments/values-stable.yaml
Release rc3 to main
To have the latest changes in main
N/A
=> release(1.6.0-RC3): merge release -> main

charts/portal/templates/deployment-frontend-portal.yaml
create new env variable for managed identity wallet
support url in the other portal apps
NA
[Link to pull request from other repository.](https://github.com/eclipse-tractusx/portal-frontend/pull/162)
=> updates(env): add managed identity wallet new url

CHANGELOG.md, README.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml
update readme for v1.6.0-RC5
update changelog for v1.6.0-RC5
To prepare the branch for the release
N/A
=> release: update readme for v1.6.0-RC5

.tractusx
update tractusx metadata file for shared UI components repository
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5/
https://github.com/eclipse-tractusx/portal-cd/issues/66
=> chore(shared-components): update tx metadata

CHANGELOG.md, README.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml
merge v1.6.0-RC6 in release-candidate branch
merge the latest changes to the release candidate
N/A
=> release: merge v1.6.0-RC6 in rc

.github/workflows/portal-chart-test.yaml, .tractusx, NOTICE.md, charts/chart-testing-config.yaml
- update notice file
- add file headers
https://github.com/eclipse-tractusx/portal-cd/issues/66#issuecomment-1681999909
https://github.com/eclipse-tractusx/portal-cd/issues/71
=> chore: update notice file and add file headers

CHANGELOG.md, README.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml
=> release(1.6.0-RC7): finalize version

charts/portal/templates/deployment-backend-appmarketplace.yaml
Corrected the typo Issue for submitappdocumenttypeids.
Validation was failing for app_leadimage for submitappdocumenttypeIds and allowing to execute the end point
CPLP-2981.
=> fix(apprelease): put app submit 

CHANGELOG.md, README.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml
=> release(1.6.0-RC8): finalize version

charts/portal/values.yaml
update bpdm api path from /api to /pool/api.
bpdm path has been updated
NA
=> chore(bdpm): update bpdm api path value 

CHANGELOG.md, README.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml
merge release branch in main for 1.6.0 version.
to wrap up release process for 1.6.0 version.
n/a
=> release(1.6.0): merge release in main

SECURITY.md
update security.md
https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01/#security-file
=> chore: update security.md

consortia/environments/values-beta.yaml, consortia/environments/values-dev.yaml, consortia/environments/values-int.yaml, consortia/environments/values-pen.yaml, consortia/environments/values-rc.yaml, consortia/environments/values-stable.yaml
Fix the path to each secret of the onboarding service provider
Currently the link is not environment specific
N/A - Jira Issue: CPLP-2638
=> chore: fix secret values for osp

charts/portal/templates/deployment-backend-appmarketplace.yaml, charts/portal/templates/deployment-backend-services.yaml
Added activationPortalAddress url
Added activationPortalAddress url for email notification
N/A Ref : CPLP-3202
[Link to pull request from other repository.](https://github.com/eclipse-tractusx/portal-backend/pull/272)
=> chore(app&service) : added activationPortalAddress url

.github/workflows/portal-chart-test.yaml, charts/portal/templates/secret-backend-external-db.yaml, charts/portal/templates/secret-backend-interfaces.yaml, charts/portal/templates/secret-backend-keycloak.yaml, charts/portal/templates/secret-backend-mailing.yaml, charts/portal/templates/secret-backend-postgres-init.yaml, charts/portal/values.yaml, consortia/environments/values-beta.yaml, consortia/environments/values-dev.yaml, consortia/environments/values-int.yaml, consortia/environments/values-pen.yaml, consortia/environments/values-rc.yaml
- change to ingress.className: wrongly changed to ingress.ingressClassName when removing deprecated ingress annotation 'kubernetes.io/ingress.class'
- fix escaping of secret values
- set database healthchecks in default values file
- update k8s version and version to upgrade from for helm test workflow
n.a
=> chores(portal-chart): change config (e.g. database healthchecks) and upgrade helm test

charts/portal/values.yaml
fixed typo error in subscription manager role
fixed typo error in subscription manager role
N/A Ref : CPLP-3111
[Link to pull request from other repository.](https://github.com/eclipse-tractusx/portal-backend/pull/239)
=> fix(app): fixed typo error in subscriptionManagerRole

.github/workflows/localdev-chart-test.yaml, charts/localdev/Chart.yaml, charts/localdev/README.md, charts/localdev/README.md.gotmpl, charts/localdev/clusterissuer.yaml, charts/localdev/templates/configmap-backend-postgres-init.yaml, charts/localdev/templates/secret-postgres-init.yaml, charts/localdev/values.yaml
- add postgres for backend dev
- update docs for install into localdev namespace
- increase timeout for chart testing install
Improve localdev umbrella chart
relates to https://github.com/eclipse-tractusx/portal-cd/pull/90
=> feat(locadev): add postgres for backend dev

.github/workflows/chart-release.yaml, .github/workflows/localdev-chart-test.yaml, charts/localdev/Chart.yaml, charts/localdev/README.md, charts/localdev/README.md.gotmpl, charts/localdev/clusterissuer.yaml, charts/localdev/templates/centralidp-spi.yaml, charts/localdev/templates/configmap-backend-postgres-init.yaml, charts/localdev/templates/secret-postgres-init.yaml, charts/localdev/templates/sharedidp-spi.yaml, charts/localdev/values.yaml, charts/portal/values.yaml
merge release branch in main for 0.1.0 version.
to wrap up release process for 0.1.0 version.
n/a
=> release(localdev): : merge in main

.github/workflows/localdev-chart-test.yaml, charts/localdev/README.md, charts/localdev/README.md.gotmpl
improve readme
- add graph for 1rst login example
- add note for portal-migrations job failing until portal database is ready to take connections
- add option for /etc/hosts file under network setup -re-add additional mac setup (wasn't part of readme tmpl the last and got lost) 
disable helm test for push and PR as it sometimes runs successfully in 4 minutes and other times fails after 20 minutes, it's not reliable
cherry-pick commit to main to support users of the chart until the next release
The infos are harder to find in the dev branch as main is the default branch
=> docs(localdev): improve readme

.github/workflows/portal-chart-test.yaml, CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-dev.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml, consortia/environments/values-upgrade.yaml
merge release branch in main for 1.7.0-RC1 version.
to finalize release process for 1.7.0-RC1 version.
n/a
=> release(portal-1.7.0-RC1): merge in main

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
Update README
Merge the RC2 changes to the release candidate
N/A
=> release(1.7.0-RC2): finalize version

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
=> release(1.7.0-RC3): finalize version

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
=> release(portal-1.7.0-RC4): finalize version

.github/workflows/trivy.yml, CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/templates/cronjob-backend-processes.yaml, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
merge release branch in main for 1.7.0-RC4 version.
to finalize release process for 1.7.0-RC4 version.
n/a
=> release(portal-1.7.0-RC4): merge in main

.github/workflows/pullRequest-lint.yaml, CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
merge release branch in main for 1.7.0 version.
to finalize release process for 1.7.0 version.
n/a
=> release(portal-1.7.0): merge in main

.github/workflows/portal-chart-test.yaml, CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
Update README
- re-enable helm upgrade step in chart-testing: was disabled due to major postgres upgrade in subchart in previous version
N/A
=> build(portal-1.8.0-RC1): finalize version

.github/workflows/portal-chart-test.yaml, CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/templates/deployment-backend-services.yaml, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
Update README
- re-enable helm upgrade step in chart-testing: was disabled due to major postgres upgrade in subchart in previous version
Merge the latest changes to main
N/A
=> build(portal-1.8.0-RC1): merge in main

.github/workflows/portal-chart-test.yaml, CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
Merge the latest changes from main to dev
To have the latest changes available in dev
N/A
=> build(v1.8.0-RC1): merge release to dev

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
=> build(portal-1.8.0-RC2): finalize version

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
Update README
Merge the latest changes to main
N/A
=> build(portal-1.8.0-RC2): merge in main

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
Merge the latest changes from main to dev
To have the latest changes available in dev
N/A
=> build(v1.8.0-RC2): merge release to dev

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
=> build(portal-1.8.0-RC3): finalize version

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
=> build(portal-1.8.0-RC4): finalize version

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
Update README
Merge the latest changes to main
N/A
=> build(portal-1.8.0-RC4): merge in main

CHANGELOG.md, charts/localdev/Chart.yaml, charts/localdev/README.md, charts/localdev/values.yaml, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
Merge the latest changes from main to dev
To have the latest changes available in dev
https://github.com/eclipse-tractusx/portal-cd/issues/151
=> build(v1.8.0-RC4): merge release to dev

CHANGELOG.md, charts/portal/templates/cronjob-backend-portal-maintenance.yaml, charts/portal/templates/cronjob-backend-processes.yaml, charts/portal/templates/deployment-backend-administration.yaml, charts/portal/templates/deployment-backend-appmarketplace.yaml, charts/portal/templates/deployment-backend-notification.yaml, charts/portal/templates/deployment-backend-registration.yaml, charts/portal/templates/deployment-backend-services.yaml, charts/portal/templates/deployment-frontend-assets.yaml, charts/portal/templates/deployment-frontend-portal.yaml, charts/portal/templates/deployment-frontend-registration.yaml, charts/portal/templates/job-backend-portal-migrations.yaml, charts/portal/templates/job-backend-provisioning-migrations.yaml, charts/portal/values.yaml
- make imagePullPolicy configurable, default set to IfNotPresent
- add registry for image name
https://github.com/eclipse-tractusx/portal-cd/issues/171
=> chore: make imagePullPolicy configurable and registry to image

charts/portal/templates/deployment-backend-administration.yaml, charts/portal/templates/deployment-backend-appmarketplace.yaml, charts/portal/templates/deployment-backend-notification.yaml, charts/portal/templates/deployment-backend-registration.yaml, charts/portal/templates/deployment-backend-services.yaml, charts/portal/values.yaml
add api-basePath to configuration of all services.
required for code-change in backend (addition of common endpoint for error-messages, new common definition of api-basePath)
N/A
Link to backend-PR:
https://github.com/eclipse-tractusx/portal-backend/pull/494
=> feat(routing): add api basePath for all services

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
Update README
https://github.com/eclipse-tractusx/portal-cd/issues/167
=> build(portal-1.8.0-RC6): finalize version

charts/portal/templates/_helpers.tpl, charts/portal/templates/configmap-backend-postgres-init.yaml, charts/portal/templates/cronjob-backend-portal-maintenance.yaml, charts/portal/templates/cronjob-backend-processes.yaml, charts/portal/templates/deployment-backend-administration.yaml, charts/portal/templates/deployment-backend-appmarketplace.yaml, charts/portal/templates/deployment-backend-notification.yaml, charts/portal/templates/deployment-backend-registration.yaml, charts/portal/templates/deployment-backend-services.yaml, charts/portal/templates/deployment-frontend-assets.yaml, charts/portal/templates/deployment-frontend-portal.yaml, charts/portal/templates/deployment-frontend-registration.yaml, charts/portal/templates/ingress-backend.yaml, charts/portal/templates/ingress-frontend.yaml, charts/portal/templates/job-backend-portal-migrations.yaml, charts/portal/templates/job-backend-provisioning-migrations.yaml, charts/portal/templates/secret-backend-external-db.yaml, charts/portal/templates/secret-backend-interfaces.yaml, charts/portal/templates/secret-backend-keycloak.yaml, charts/portal/templates/secret-backend-mailing.yaml, charts/portal/templates/secret-backend-postgres-init.yaml, charts/portal/templates/service-backend-administration.yaml, charts/portal/templates/service-backend-appmarketplace.yaml, charts/portal/templates/service-backend-notification.yaml, charts/portal/templates/service-backend-registration.yaml, charts/portal/templates/service-backend-services.yaml, charts/portal/templates/service-frontend-assets.yaml, charts/portal/templates/service-frontend-portal.yaml, charts/portal/templates/service-frontend-registration.yaml, charts/portal/values.yaml
Reverts eclipse-tractusx/portal-cd#189
Need to improve Ingress --> Service --> Pod connection
=> fix: revert "feat(helm-chart): define unique resource names"

charts/portal/templates/_helpers.tpl, charts/portal/templates/configmap-backend-postgres-init.yaml, charts/portal/templates/cronjob-backend-portal-maintenance.yaml, charts/portal/templates/cronjob-backend-processes.yaml, charts/portal/templates/deployment-backend-administration.yaml, charts/portal/templates/deployment-backend-appmarketplace.yaml, charts/portal/templates/deployment-backend-notification.yaml, charts/portal/templates/deployment-backend-registration.yaml, charts/portal/templates/deployment-backend-services.yaml, charts/portal/templates/deployment-frontend-assets.yaml, charts/portal/templates/deployment-frontend-portal.yaml, charts/portal/templates/deployment-frontend-registration.yaml, charts/portal/templates/ingress-backend.yaml, charts/portal/templates/ingress-frontend.yaml, charts/portal/templates/job-backend-portal-migrations.yaml, charts/portal/templates/job-backend-provisioning-migrations.yaml, charts/portal/templates/secret-backend-external-db.yaml, charts/portal/templates/secret-backend-interfaces.yaml, charts/portal/templates/secret-backend-keycloak.yaml, charts/portal/templates/secret-backend-mailing.yaml, charts/portal/templates/secret-backend-postgres-init.yaml, charts/portal/templates/service-backend-administration.yaml, charts/portal/templates/service-backend-appmarketplace.yaml, charts/portal/templates/service-backend-notification.yaml, charts/portal/templates/service-backend-registration.yaml, charts/portal/templates/service-backend-services.yaml, charts/portal/templates/service-frontend-assets.yaml, charts/portal/templates/service-frontend-portal.yaml, charts/portal/templates/service-frontend-registration.yaml, charts/portal/values.yaml
- define unique templates
- define unique resource names for deployment, jobs, services and ingresses
- add labels and namespace if not already set
improve chart
https://github.com/eclipse-tractusx/portal-cd/issues/190
https://github.com/eclipse-tractusx/portal-cd/pull/192
=> feat(helm-chart): define unique resource names

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
Update README
https://github.com/eclipse-tractusx/portal-cd/issues/168
=> build(portal-1.8.0-RC7): finalize version

CHANGELOG.md, charts/portal/templates/_helpers.tpl, charts/portal/templates/cronjob-backend-portal-maintenance.yaml, charts/portal/templates/cronjob-backend-processes.yaml, charts/portal/templates/deployment-backend-administration.yaml, charts/portal/templates/deployment-backend-appmarketplace.yaml, charts/portal/templates/deployment-backend-notification.yaml, charts/portal/templates/deployment-backend-registration.yaml, charts/portal/templates/deployment-backend-services.yaml, charts/portal/templates/ingress-backend.yaml, charts/portal/templates/ingress-frontend.yaml, charts/portal/templates/job-backend-portal-migrations.yaml, charts/portal/templates/job-backend-provisioning-migrations.yaml
- define unique templates
- use templates for db access (subchart)
- change template in ingresses
preparation for https://github.com/eclipse-tractusx/portal-cd/issues/190 and https://github.com/eclipse-tractusx/portal-cd/issues/191
=> chore: define unique templates and use for db access (subchart)

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/templates/_helpers.tpl, charts/portal/templates/cronjob-backend-portal-maintenance.yaml, charts/portal/templates/cronjob-backend-processes.yaml, charts/portal/templates/deployment-backend-administration.yaml, charts/portal/templates/deployment-backend-appmarketplace.yaml, charts/portal/templates/deployment-backend-notification.yaml, charts/portal/templates/deployment-backend-registration.yaml, charts/portal/templates/deployment-backend-services.yaml, charts/portal/templates/ingress-backend.yaml, charts/portal/templates/ingress-frontend.yaml, charts/portal/templates/job-backend-portal-migrations.yaml, charts/portal/templates/job-backend-provisioning-migrations.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
https://github.com/eclipse-tractusx/portal-cd/issues/168
=> build(portal-1.8.0-RC8): merge release into main

.tractusx, NOTICE.md, charts/portal/Chart.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-dev.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-rc.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
change portal-cd references to portal
TRG-2.04 compliance
https://github.com/eclipse-tractusx/portal-cd/issues/131
=> chore(trg-2.04): change portal-cd references to portal

.github/workflows/localdev-chart-test.yaml, .github/workflows/portal-chart-test.yaml, charts/portal/Chart.yaml, charts/portal/values.yaml, charts/values-test.yaml
- db-dependency:
- change setup to get latest minor updates
- remove fullnameOverride
- name secrets more uniquely
- helm-test: 
- enable for removal for fullnameOverride and renaming for postgres secret
- update version to upgrade from and k8s version
https://github.com/eclipse-tractusx/portal/issues/191
https://github.com/eclipse-tractusx/portal/issues/190
=> chore: improve db-dependency and rename secrets

charts/portal/templates/cronjob-backend-processes.yaml
fix secret key of onboardingserviceprovider encrpytionkey
key got renamed as part of https://github.com/eclipse-tractusx/portal/pull/214
na
=> fix(processes-worker): fix secret key of osp encrpytionkey

charts/portal/values.yaml
chore(processesworker): increase resource limits
OOM on dev env
https://github.com/eclipse-tractusx/portal/issues/207
=> chore(processesworker): increase resource limits

charts/portal/templates/_helpers.tpl, charts/portal/values.yaml
chore: increase memory for appmarketplace and processesworker
#228
=> chore: increase memory for appmarketplace and processesworker

charts/portal/values.yaml
increase memory for migrations and maintenance job
https://github.com/eclipse-tractusx/portal/issues/207
=> chore: increase memory for migrations and maintenance job

charts/portal/templates/cronjob-backend-processes.yaml, charts/portal/templates/deployment-backend-administration.yaml, charts/portal/templates/deployment-backend-registration.yaml, charts/portal/templates/deployment-frontend-portal.yaml, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/environments/values-beta.yaml, consortia/environments/values-dev.yaml, consortia/environments/values-int.yaml, consortia/environments/values-pen.yaml, consortia/environments/values-rc.yaml
- change bpdm pool api path and improve configuration
- move bpdm api paths into config / helm chart from backend --> backend change https://github.com/eclipse-tractusx/portal-backend/pull/644
https://github.com/eclipse-tractusx/portal/issues/248
=> chore: change bpdm api path and improve configuration

charts/portal/templates/deployment-backend-administration.yaml
Activate the dim wallet creation
To use the dim wallet instead of the custodian implementation
N/A
=> feat(dim): activate dim wallet creation

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
=> build(portal-2.0.0-RC2): finalize version

consortia/environments/values-int.yaml, consortia/environments/values-rc.yaml
activate dim wallet for int and rc environment
we want to use the new dim wallet
N/A
=> feat: activate dim wallet

charts/portal/values.yaml, consortia/environments/values-dev.yaml, consortia/environments/values-int.yaml, consortia/environments/values-pen.yaml, consortia/environments/values-rc.yaml
change bpn did resolver management api address
follow to https://github.com/eclipse-tractusx/portal/pull/245
https://github.com/eclipse-tractusx/portal-backend/issues/572
=> chore: change bpn did resolver management api address

charts/portal/templates/cronjob-backend-processes.yaml, charts/portal/templates/deployment-backend-administration.yaml, charts/portal/templates/deployment-backend-appmarketplace.yaml, charts/portal/templates/deployment-backend-services.yaml, charts/portal/values.yaml, consortia/environments/values-beta.yaml, consortia/environments/values-dev.yaml, consortia/environments/values-int.yaml, consortia/environments/values-pen.yaml, consortia/environments/values-rc.yaml
Add baseAddress for the dim wrapper
To have the correct url set for the dim wrapper on each environment
N/A
=> fix(dim): add baseAddress for dim

charts/portal/templates/deployment-backend-administration.yaml, charts/portal/values.yaml, consortia/environments/values-beta.yaml, consortia/environments/values-dev.yaml, consortia/environments/values-int.yaml, consortia/environments/values-pen.yaml, consortia/environments/values-rc.yaml
Add Dim Management Url to configuration
To support the backend changes
Refs: #643
=> feat(dim): add dim management url config

charts/portal/templates/cronjob-backend-processes.yaml
adjust config for the bpn did resolver
The configuration was moved by the portal backend
N/A
=> fix(bpnDidResolver): adjust config

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
=> build(portal-2.0.0-RC3): finalize version

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
=> build(portal-2.0.0-RC4): finalize version

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
=> build(portal-2.0.0-RC4): merge release into main

charts/portal/templates/deployment-frontend-portal.yaml, charts/portal/values.yaml
chore(credential-issuer): add client id
https://github.com/eclipse-tractusx/portal-frontend/issues/620
Link to pull request from other repository: https://github.com/eclipse-tractusx/portal-frontend/pull/738
=> chore(credential-issuer): add client id

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
=> build(portal-2.0.0-RC5): finalize version

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/templates/deployment-frontend-portal.yaml, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml, consortia/environments/values-dev.yaml, consortia/environments/values-int.yaml, consortia/environments/values-pen.yaml, consortia/environments/values-rc.yaml
=> build(portal-2.0.0-RC5): merge release into main

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
=> build(portal-2.0.0-RC6): finalize version

.github/workflows/administration-service-image-update.yml, .github/workflows/chart-release.yaml, .github/workflows/kics.yml, .github/workflows/localdev-chart-test.yaml, .github/workflows/maintenance-service-image-update.yml, .github/workflows/marketplace-app-service-image-update.yml, .github/workflows/notification-service-image-update.yml, .github/workflows/portal-assets-image-update.yml, .github/workflows/portal-backend-release-image-update.yml, .github/workflows/portal-chart-test.yaml, .github/workflows/portal-image-update.yml, .github/workflows/portal-migrations-image-update.yml, .github/workflows/portal-registration-image-update.yml, .github/workflows/processes-worker-image-update.yml, .github/workflows/provisioning-migrations-image-update.yml, .github/workflows/pullRequest-lint.yaml, .github/workflows/registration-service-image-update.yml, .github/workflows/services-service-image-update.yml, .github/workflows/trivy.yml, CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
=> build(2.0.0-rc9): finalize version

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
=> build(2.0.0-rc10): bump version and update docs

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
=> build(2.0.0-rc10): merge release into main

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
finalize version 2.0.0
https://github.com/eclipse-tractusx/sig-release/issues/671
=> build(2.0.0): bump version and update docs

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/templates/cronjob-backend-processes.yaml, charts/portal/templates/deployment-backend-administration.yaml, charts/portal/templates/deployment-backend-appmarketplace.yaml, charts/portal/templates/deployment-backend-notification.yaml, charts/portal/templates/deployment-backend-registration.yaml, charts/portal/templates/deployment-backend-services.yaml, charts/portal/templates/deployment-frontend-portal.yaml, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-beta.yaml, consortia/argocd-app-templates/appsetup-int.yaml, consortia/argocd-app-templates/appsetup-pen.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/argocd-app-templates/appsetup-upgrade.yaml
Merge the latest changes to the dev branch
To have the latest changes available in the dev branch
NA
=> build(2.0.0): merge main into dev

charts/localdev/Chart.yaml, charts/localdev/README.md, charts/localdev/values.yaml
change localdev to 24.05 release
enable local development
na
=> build(localdev-0.5.0): change to 24.05 release

charts/portal/templates/deployment-frontend-portal.yaml
add new values for bpdm pool and company urls.
remove existing value from chart
related change in the portal frontend: https://github.com/eclipse-tractusx/portal-frontend/pull/731
https://github.com/eclipse-tractusx/portal-frontend/issues/623
=> feat: add new values for bpdm pool and company urls

charts/portal/templates/deployment-backend-administration.yaml, charts/portal/templates/deployment-backend-notification.yaml, charts/portal/templates/secret-backend-keycloak.yaml, charts/portal/values.yaml, consortia/argocd-app-templates/appsetup-stable.yaml, consortia/environments/values-beta.yaml, consortia/environments/values-dev.yaml, consortia/environments/values-int.yaml, consortia/environments/values-pen.yaml, consortia/environments/values-rc.yaml
remove obsolete centralidp database configuration
https://github.com/eclipse-tractusx/portal/issues/351
=> chore(portal): remove obsolete centralidp database configuration

charts/portal/values.yaml
increase memory for services service
https://github.com/eclipse-tractusx/portal/issues/352
=> fix: increase memory for services service

charts/portal/templates/deployment-backend-administration.yaml
fix brds address shown in the connector management section of the frontend
https://github.com/eclipse-tractusx/portal/issues/363
=> fix(bdrs-url): change to directoryApiAddress

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, environments/argocd-app-templates/appsetup-int.yaml, environments/consortia/argocd-app-templates/appsetup-int.yaml
finalize version 2.1.0-RC1
https://github.com/eclipse-tractusx/portal/issues/350
=> build(2.1.0-rc1): bump version and update docs

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, environments/argocd-app-templates/appsetup-int.yaml, environments/consortia/argocd-app-templates/appsetup-int.yaml
finalize version 2.1.0-RC2
https://github.com/eclipse-tractusx/portal/issues/350
=> build(2.1.0-RC2): bump version and update docs

environments/consortia/helm-values/values-dev.yaml, environments/consortia/helm-values/values-int.yaml, environments/consortia/helm-values/values-rc.yaml
fix secret path for consortia envs
got misconfigured with https://github.com/eclipse-tractusx/portal/pull/368
https://github.com/eclipse-tractusx/portal/issues/350
=> chore: fix secret path for consortia envs

environments/helm-values/values-int.yaml
add did for displaying in frontend
https://github.com/eclipse-tractusx/portal/issues/349
=> chore(association-env): add did for displaying in frontend

charts/portal/values.yaml
add information for the clearinghouseConnectDisabled flag
To give a better understanding of the flag and the results of changing it.
Refs: #386
=> docs: add information for the clearinghouseConnectDisabled flag

CHANGELOG.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, environments/argocd-app-templates/appsetup-int.yaml, environments/consortia/argocd-app-templates/appsetup-int.yaml
finalize version 2.1.0-RC3
https://github.com/eclipse-tractusx/portal/issues/380
=> build(2.1.0-rc3): bump version and update docs

CHANGELOG.md, charts/localdev/Chart.yaml, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, environments/argocd-app-templates/appsetup-int.yaml, environments/helm-values/values-int.yaml
finalize version 2.2.0-RC1
https://github.com/eclipse-tractusx/portal/issues/398
=> build(2.2.0-rc1): bump version and update docs

CHANGELOG.md, charts/localdev/Chart.yaml, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, environments/argocd-app-templates/appsetup-int.yaml, environments/helm-values/values-int.yaml
https://github.com/eclipse-tractusx/portal/issues/398
=> build(2.2.0-rc1): merge release into main

CHANGELOG.md, charts/localdev/Chart.yaml, charts/localdev/README.md, charts/localdev/README.md.gotmpl, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, environments/argocd-app-templates/appsetup-int.yaml
finalize version 2.2.0-RC2
https://github.com/eclipse-tractusx/portal/issues/398
=> build(2.2.0-rc2): bump version and update docs

CHANGELOG.md, charts/localdev/Chart.yaml, charts/localdev/README.md, charts/localdev/README.md.gotmpl, charts/localdev/values.yaml, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, environments/argocd-app-templates/appsetup-int.yaml
https://github.com/eclipse-tractusx/portal/issues/398
=> build(2.2.0-rc2): merge release into main

CHANGELOG.md, charts/localdev/Chart.yaml, charts/localdev/README.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, environments/argocd-app-templates/appsetup-int.yaml
* update changelog for v2.2.0-RC3
* bump version to v2.2.0-RC3
To finalise v2.2.0-RC3
N/A
=> build(2.2.0-rc3): bump version and update docs

CHANGELOG.md, charts/localdev/Chart.yaml, charts/localdev/README.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/templates/cronjob-backend-processes.yaml, charts/portal/values.yaml, environments/argocd-app-templates/appsetup-int.yaml
Merge the latest release into main
N/A
=> build: merge release into main

CHANGELOG.md, charts/localdev/Chart.yaml, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, environments/argocd-app-templates/appsetup-int.yaml
finalize version 2.2.0
https://github.com/eclipse-tractusx/portal/issues/423
=> build(2.2.0): bump version and  update docs

CHANGELOG.md, charts/localdev/Chart.yaml, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, environments/argocd-app-templates/appsetup-int.yaml
=> build(2.2.0): merge release into main

CHANGELOG.md, charts/localdev/Chart.yaml, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, environments/argocd-app-templates/appsetup-int.yaml
https://github.com/eclipse-tractusx/portal/issues/433
=> build(2.3.0-alpha.1): merge release into main

CHANGELOG.md, charts/localdev/Chart.yaml, charts/localdev/README.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, environments/argocd-app-templates/appsetup-int.yaml
https://github.com/eclipse-tractusx/portal/issues/444
=> build(2.3.0-alpha.2): merge release into main

charts/localdev/Chart.yaml, charts/localdev/README.md, charts/localdev/README.md.gotmpl, charts/localdev/values-tls.yaml, charts/localdev/values.yaml
- upgrade iam instances to v4.0.0-alpha.1
- enable separate values file with prepared tls enabled
#453
=> chore(localdev): upgrade iam instances to v4.0.0-alpha.1 

environments/argocd-app-templates/appsetup-stable.yaml, environments/helm-values/values-stable.yaml
This PR introduces configurations for the stable environment adapted to the main branch. 
relates to https://github.com/eclipse-tractusx/portal/issues/408
=> build: Add configuration for stable environment

CHANGELOG.md, charts/localdev/Chart.yaml, charts/localdev/README.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, environments/argocd-app-templates/appsetup-int.yaml, environments/argocd-app-templates/appsetup-stable.yaml
=> build(2.3.0-alpha.3): merge release into main

CHANGELOG.md, charts/localdev/Chart.yaml, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, environments/argocd-app-templates/appsetup-int.yaml, environments/argocd-app-templates/appsetup-stable.yaml
finalize version 2.3.0-RC1 by merge into main
https://github.com/eclipse-tractusx/portal/issues/465
=> build(2.3.0-rc1): bump version and update docs

charts/portal/values.yaml
change operator default information
follow up to https://github.com/eclipse-tractusx/portal/pull/450
https://github.com/eclipse-tractusx/portal/issues/449
=> fix: change operator default information

.github/workflows/trivy.yml, CHANGELOG.md, charts/localdev/Chart.yaml, charts/localdev/README.md, charts/localdev/values-tls.yaml, charts/localdev/values.yaml, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, environments/argocd-app-templates/appsetup-int.yaml, environments/argocd-app-templates/appsetup-stable.yaml, environments/helm-values/values-int.yaml, environments/helm-values/values-stable.yaml
finalize version
https://github.com/eclipse-tractusx/portal/issues/465
=> build(2.3.0-rc3): bump version and update docs

.github/workflows/trivy.yml, CHANGELOG.md, charts/localdev/Chart.yaml, charts/localdev/README.md, charts/localdev/values-tls.yaml, charts/localdev/values.yaml, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, environments/argocd-app-templates/appsetup-int.yaml, environments/argocd-app-templates/appsetup-stable.yaml, environments/helm-values/values-int.yaml, environments/helm-values/values-stable.yaml
=> build(2.3.0-rc4): merge release into main

charts/portal/values.yaml
New path is /tagus instead of /rel3.
New tagus sd-factory.
Refs: eclipse-tractusx/sig-release#993
=> feat(sd-factory): update path for tagus

charts/portal/templates/deployment-backend-appmarketplace.yaml, charts/portal/templates/deployment-backend-services.yaml, charts/portal/values.yaml, environments/helm-values/values-stable.yaml
- increase memory for services service 
- envs: set dim token address for stable
- change did base location for app and services service
various configuration findings noticed recently
n/a
=> fix: resolve various configuration findings

CHANGELOG.md, charts/localdev/Chart.yaml, charts/localdev/README.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, environments/argocd-app-templates/appsetup-int.yaml, environments/argocd-app-templates/appsetup-stable.yaml
=> build(2.4.0): merge release into main

CHANGELOG.md, charts/localdev/Chart.yaml, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/values.yaml, environments/argocd-app-templates/appsetup-int.yaml, environments/argocd-app-templates/appsetup-stable.yaml
To have the latest changes
#541
=> build(2.5.0-RC1): bump version and update docs

CHANGELOG.md, charts/localdev/Chart.yaml, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/values.yaml, environments/argocd-app-templates/appsetup-int.yaml, environments/argocd-app-templates/appsetup-stable.yaml
To have the latest changes
#541
=> build(2.5.0-RC1): merge latest changes in main

CHANGELOG.md, charts/localdev/Chart.yaml, charts/localdev/README.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/README.md.gotmpl, charts/portal/values.yaml, environments/argocd-app-templates/appsetup-int.yaml, environments/argocd-app-templates/appsetup-stable.yaml
=> build(2.5.0): merge release into main 

.github/workflows/portal-chart-test.yaml, CHANGELOG.md, charts/localdev/Chart.yaml, charts/localdev/README.md, charts/localdev/values.yaml, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/values.yaml
- change bitnami image path to legacy repository
- update localdev to use updated dependencies
Bitnami now requires a paid subscription to use their images. 
Closes: #562
=> build(2.6.0-RC2): change bitnami image repository and update localdev

CHANGELOG.md, charts/localdev/Chart.yaml, charts/localdev/README.md, charts/portal/Chart.yaml, charts/portal/README.md, charts/portal/values.yaml, environments/argocd-app-templates/appsetup-int.yaml, environments/argocd-app-templates/appsetup-stable.yaml
finalize version for R25.09
#567
=> build(2.6.0): bump version and update docs
