- charts/portal/values.yaml
change container registry from to ghcr.io/catenax-ng to dockerhub 'tractusx'.
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-05
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06
Related:
https://github.com/eclipse-tractusx/portal-cd/pull/13
https://github.com/eclipse-tractusx/portal-frontend/pull/19
https://github.com/eclipse-tractusx/portal-frontend-registration/pull/19
https://github.com/eclipse-tractusx/portal-assets/pull/13
https://github.com/eclipse-tractusx/portal-backend/pull/27
> chore(dockerhub): change container registry

- charts/portal/values.yaml
- consortia/environments/values-beta.yaml
- consortia/environments/values-dev.yaml
- consortia/environments/values-int.yaml
- consortia/environments/values-pen.yaml
- consortia/environments/values-preprod.yaml
- consortia/environments/values-rc.yaml
move increase of max_connections for db-dependency to consortia environments and add note for max_connections recommendation increase to default values file
max_connections for db-dependency is to be considered a env specific configuration
also: to be avoid issues at upgrade
n/a
ref: CPLP-2739
https://github.com/eclipse-tractusx/portal-cd/pull/19
> chore(db-dependency): move max_connections increase to consortia

- .github/workflows/portal-chart-test.yaml
- charts/portal/values.yaml
- enable testing of helm upgrade from different portal chart versions via workflow dispatch (default version set to the portal version 1.3.0,  from the latest tx release aka 3.1)
- enable testing with different k8s version via workflow dispatch (default version set to 1.24.6, as the 3.1 release was tested with that version)
- update helm test workflow as [trg helm test](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09) was updated since introduction of the workflow
- uncomment and use list-changed step and improve for workflow dispatch usage
[trg upgradeability](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-11)
[trg k8s versions](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-10)
n/a
> chore(trg-helm): improve helm test workflow

- charts/portal/templates/deployment-backend-registration.yaml
- charts/portal/values.yaml
Added Configuration for document type Ids for submit registration end point in registration service
backend PR is https://github.com/eclipse-tractusx/portal-backend/pull/82
Setting is required to avoid hard coded value in code and can be configured at any time
CPLP-2736
> fix(registration): configuration for documenttypeids for submitregistration

- charts/portal/templates/job-backend-portal-migrations.yaml
- charts/portal/values.yaml
Added configuration for the seeding to use the Seeder/Data directory
To be able to seed ones own data and don't have the need to edit the json files within the Seeder/Data directory one can now mount a directory which than can be configured to be used for the seeding as well.
N/A - Jira Issue: CPLP-2788
[#108](https://github.com/eclipse-tractusx/portal-backend/pull/108)
> feat(seeding): add configuration for seeding path

- charts/portal/templates/deployment-backend-administration.yaml
- charts/portal/templates/deployment-backend-appmarketplace.yaml
- charts/portal/templates/deployment-backend-registration.yaml
- charts/portal/templates/deployment-backend-services.yaml
fix name of environment variables for logging
when moving from catenax-ng to eclipse-tractusx GH org the renaming of some package names must have been forgotten in the config
n/a
> fix(logging): change name of env variables

- charts/portal/templates/cronjob-backend-portal-maintenance.yaml
- charts/portal/templates/cronjob-backend-processes.yaml
- charts/portal/templates/job-backend-portal-migrations.yaml
- charts/portal/values.yaml
add configuration values for the process identity for maintenance, migrations and process worker
To support the new process identity in the backend the new config values needed to be added
N/A - Jira Issue: CPLP-2960
[#147](https://github.com/eclipse-tractusx/portal-backend/pull/147)
> chore: add process identity config values

- charts/portal/values.yaml
Add documentation for seeding testDataPaths
If changing the testDataPaths for the seeding the processIdentity needs to be adjusted as well
N/A
[#214](https://github.com/eclipse-tractusx/portal-backend/pull/214)
> chore: add documentation for seeding testDataPaths

- charts/portal/templates/deployment-backend-appmarketplace.yaml
fixed subscriptionManagerRoles
fixed  subscriptionManagerRoles to fetch the clientid
N/A Ref : CPLP-3111
[Link to pull request from other repository.](https://github.com/eclipse-tractusx/portal-backend/pull/239)
> fix(apps) : fixed subscriptionManagerRoles

- charts/portal/templates/secret-backend-external-db.yaml
- charts/portal/templates/secret-backend-interfaces.yaml
- charts/portal/templates/secret-backend-keycloak.yaml
- charts/portal/templates/secret-backend-mailing.yaml
- charts/portal/templates/secret-backend-postgres-init.yaml
fix placement of quotes for escaping
fix wrong key for [process-onboardingprovider](https://github.com/eclipse-tractusx/portal-cd/pull/101/files#diff-7f9045318b32510da44cb93dc7bfa26b1806adfc0e1e3879f02f38925d657e27R39)
led to empty values at helm upgrade
relates to https://github.com/eclipse-tractusx/portal-cd/pull/90
> fix(secrets): move quotes for escaping

- charts/localdev/Chart.yaml
- charts/localdev/README.md
- charts/localdev/README.md.gotmpl
- charts/localdev/templates/centralidp-spi.yaml
- charts/localdev/templates/sharedidp-spi.yaml
- charts/localdev/values.yaml
- upgrade portal from v1.6.0 to v1.7.0-alpha
- upgrade and enable iam instances from v1.2.0 to v2.0.0-alpha
- update documentation: remove note for cpu arch incompatibility for mac as all images are now also available for arm64
Improve localdev umbrella chart
relates to https://github.com/eclipse-tractusx/portal-cd/pull/90
> chore(localdev): upgrade and enable subcharts

- charts/portal/templates/cronjob-backend-processes.yaml
Added base portal url to the network process
To have the basePortalUrl accessible in the network process
N/A - Jira Issue: CPLP-3295
[#280](https://github.com/eclipse-tractusx/portal-backend/pull/280)
> chore: add baseportal configuration

- .github/workflows/localdev-chart-test.yaml
- charts/localdev/README.md
- charts/localdev/README.md.gotmpl
- improve readme:
- add graph for 1rst login example
- add note for portal-migrations job failing until portal database is ready to take connections
- add option for /etc/hosts file under network setup
- re-add additional mac setup (wasn't part of readme tmpl the last and got lost)
- disable helm test for push and PR as it sometimes runs successfully in 4 minutes and other times fails after 20 minutes, it's not reliable
improve LocalDev umbrella chart
relates to https://github.com/eclipse-tractusx/portal-cd/pull/90
> docs(localdev): improve readme

- .github/workflows/portal-chart-test.yaml
- charts/portal/Chart.yaml
- consortia/argocd-app-templates/appsetup-upgrade.yaml
- consortia/environments/values-upgrade.yaml
- update postgres subchart from v14.5 to v15.4
Bitnami chart version [12.12.x](https://artifacthub.io/packages/helm/bitnami/postgresql/12.12.10)
- add values file to upgrade subchart (enable blue/green deployment)
- disable upgrade step in helm test: due to major postgres upgrade the step inevitability fails
Align for 23.12 release on Postgres v15, prepare testing phase with that version
relates to keycloak upgrade which comes with upgrade of postgres subchart https://github.com/eclipse-tractusx/portal-iam/pull/20
and was blocked by https://github.com/eclipse-tractusx/portal-backend/pull/300
> chore(portal): update postgres subchart v15.4

- charts/portal/values.yaml
- consortia/argocd-app-templates/appsetup-dev.yaml
- consortia/argocd-app-templates/appsetup-int.yaml
- consortia/argocd-app-templates/appsetup-upgrade.yaml
- consortia/environments/values-upgrade.yaml
revert db name change for subchart
and upgrade argoCd apptemplates
noticed after https://github.com/eclipse-tractusx/portal-cd/pull/107 that name change wasn't necessary.
> fix(portal): revert db name change for subchart

- charts/portal/templates/cronjob-backend-processes.yaml
Adjustig the application activation login link
Currently the wrong environment variable is set, therefore the link isn't set correctly and will be empty in the mail
N/A - Jira Issue: CPLP-3525
> fix(activation): adjust mail link

- charts/portal/README.md
- charts/portal/templates/cronjob-backend-portal-maintenance.yaml
- charts/portal/templates/cronjob-backend-processes.yaml
- charts/portal/templates/job-backend-portal-migrations.yaml
- charts/portal/values.yaml
Some of the values required to configure the processIdentity were removed in the backend, therefor the configurations were removed in the cd repo as well.
The determination of the needed values is made in the backend.
N/A - Jira Issue: CPLP-3102
[#361](https://github.com/eclipse-tractusx/portal-backend/pull/361)
> chore: slimline process identity config

- charts/portal/values.yaml
This PR includes configuration for new endpoint api/registration/applications/declinedata
Corresponding backend-PR: https://github.com/eclipse-tractusx/portal-backend/pull/385
new configuration-values are mandatory for startup of registrationservice.
N/A
https://github.com/eclipse-tractusx/portal-backend/pull/385
> feat(registration): add configuration for new decline registration data endpoint

- charts/portal/values.yaml
registration config value of applicationDeclineStatusIds have been adjusted
in PR https://github.com/eclipse-tractusx/portal-cd/pull/136 there was an incorrect value 'SELECT_COMPANY_DATA' set which is not a valid enum value. It has been changed to SELECT_COMPANY_ROLE
N/A
https://github.com/eclipse-tractusx/portal-backend/pull/388
> fix(registration-service): fix incorrect applicationDeclineStatusIds

- charts/portal/templates/deployment-backend-services.yaml
Fix the configuration for the upload service document type ids
missing minus, therefor one configuration was overwritten
N/A - Jira Issue: CPLP-3580
> fix(services): adjust upload service document type ids

- charts/portal/templates/deployment-backend-services.yaml
- charts/portal/values.yaml
enable deletion of "Conformity_Approval_Service" types.
DELETE /api/services/ServiceRelease/documents/{documentId}
enable deletion of "Conformity_Approval_Service" types.
Link to Github issue.
N/A Ref: CPLP-3652
> feat(services): add Conformity_Approval_Service to deletable documents

- charts/portal/templates/cronjob-backend-portal-maintenance.yaml
- charts/portal/templates/cronjob-backend-processes.yaml
- charts/portal/templates/deployment-backend-administration.yaml
- charts/portal/templates/deployment-backend-appmarketplace.yaml
- charts/portal/templates/deployment-backend-notification.yaml
- charts/portal/templates/deployment-backend-registration.yaml
- charts/portal/templates/deployment-backend-services.yaml
- charts/portal/templates/deployment-frontend-assets.yaml
- charts/portal/templates/deployment-frontend-portal.yaml
- charts/portal/templates/deployment-frontend-registration.yaml
- charts/portal/templates/job-backend-portal-migrations.yaml
- charts/portal/templates/job-backend-provisioning-migrations.yaml
- enable readOnlyRootFilesystem in containers
- mount tmp frontend deployment, required by nginx base image but also by 00-inject-dynamic-env.sh (executed via docker entrypoint) for [portal](https://github.com/eclipse-tractusx/portal-frontend/pull/471) and [registration app](https://github.com/eclipse-tractusx/portal-frontend-registration/pull/110)
https://eclipse-tractusx.github.io/docs/release/trg-0/trg-4-07
https://github.com/eclipse-tractusx/portal-cd/issues/159
> chore(trg-4-07): enable readOnlyRootFilesystem 

- charts/localdev/values.yaml
'portalPassword' was added to localdev values.yaml coordinates 'postgresportal.auth'
helm upgrade would fail expecting a valid string in .Values.postgresportal.auth.portalPassword
N/A
> fix: add portalPassword to postgresportal for helm upgrade

- charts/portal/templates/secret-backend-keycloak.yaml
Add shared-client-secret to secret generation if not existing
If not existing the setup fails due to a missing config value
N/A
> fix(keycloak): add shared client secret config

- charts/portal/values.yaml
Adjust the registration url to /registration/
Currently the link is set to /registration which the ingress redirects to the frontend not to the registration app
N/A
> fix(registration): set registration path with /

- charts/portal/README.md
- charts/portal/templates/deployment-backend-administration.yaml
- charts/portal/values.yaml
Adding required secret key for company certificate post endpoint
For accessing specific company certificate as per it company userId, status and types.
#468
> feat(certificate): add company certificate media type id

- charts/portal/templates/deployment-backend-appmarketplace.yaml
- charts/portal/templates/deployment-backend-notification.yaml
- charts/portal/templates/deployment-backend-registration.yaml
- charts/portal/templates/deployment-backend-services.yaml
Move the mvc routing base path configuration to a non if statement, that it's always set correctly.
The sync in argo fails due to the missing configuration
Refs: [494](https://github.com/eclipse-tractusx/portal-backend/pull/494)
> chore: always set mvc routing basepath

- .github/workflows/administration-service-image-update.yml
- .github/workflows/chart-release.yaml
- .github/workflows/kics.yml
- .github/workflows/localdev-chart-test.yaml
- .github/workflows/maintenance-service-image-update.yml
- .github/workflows/marketplace-app-service-image-update.yml
- .github/workflows/notification-service-image-update.yml
- .github/workflows/portal-assets-image-update.yml
- .github/workflows/portal-backend-release-image-update.yml
- .github/workflows/portal-chart-test.yaml
- .github/workflows/portal-image-update.yml
- .github/workflows/portal-migrations-image-update.yml
- .github/workflows/portal-registration-image-update.yml
- .github/workflows/processes-worker-image-update.yml
- .github/workflows/provisioning-migrations-image-update.yml
- .github/workflows/pullRequest-lint.yaml
- .github/workflows/registration-service-image-update.yml
- .github/workflows/services-service-image-update.yml
- .github/workflows/trivy.yml
upgrade gh actions and change to pinned actions full length commit sha
https://github.com/eclipse-tractusx/portal/issues/225
> chore(gh-actions): upgrade and change to pinned commit sha

- charts/portal/templates/cronjob-backend-processes.yaml
added serviceAccountClientPrefix for process
added serviceAccountClientPrefix for process to append the value for invitation process worker
Ref: #579
[Link to pull request from other repository.](https://github.com/eclipse-tractusx/portal-backend/pull/608)
> fix: added serviceAccountClientPrefix for process

- charts/portal/templates/cronjob-backend-processes.yaml
- charts/portal/templates/secret-backend-interfaces.yaml
- charts/portal/values.yaml
- consortia/environments/values-beta.yaml
- consortia/environments/values-dev.yaml
- consortia/environments/values-int.yaml
- consortia/environments/values-pen.yaml
- consortia/environments/values-rc.yaml
Added configuration for the bpn did resolver
To enable the bpn did resolver for the portal backend
Refs: https://github.com/eclipse-tractusx/portal-backend/issues/572
[#621](https://github.com/eclipse-tractusx/portal-backend/pull/621)
> feat(didResolver): add configuration for did resolver

- charts/portal/values.yaml
- consortia/environments/values-beta.yaml
- consortia/environments/values-dev.yaml
- consortia/environments/values-int.yaml
- consortia/environments/values-pen.yaml
- consortia/environments/values-rc.yaml
Setting the correct configuration for the apiKey of the bpnDidResolver for the environments
To set the correct api key for the bpn did resolver
N/A
> fix(bpnDidResolver): set correct config for apiKey

- charts/portal/templates/cronjob-backend-processes.yaml
- charts/portal/templates/deployment-backend-administration.yaml
Set the correct client id for the dim creation roles
Currently the dim technical user don't get created due to the wrong clientId
N/A
> fix: adjust clientId for dimcreationroles

- charts/portal/values.yaml
fix ingress to work without tls enabled and change according to TRG-5.04.
ingress couldn't be enabled without also tls being enabled and wasn't TRG compliant
n/a
> fix: change ingress to work without tls and according to TRG-5.04

- consortia/environments/values-beta.yaml
- consortia/environments/values-dev.yaml
- consortia/environments/values-int.yaml
- consortia/environments/values-pen.yaml
- consortia/environments/values-rc.yaml
Add consortia specific bdrs management url
The bdrs push to the management api fails because the generic url isn't overwritten.
Refs: [#721](https://github.com/eclipse-tractusx/portal-backend/issues/721)
> fix(bdrs): adjust bdrs management url

- charts/portal/templates/cronjob-backend-processes.yaml
added dim user roles to process worker config
The process worker currently don't start up
N/A
> fix(processWorker): add dimUserRoles to process config

- charts/portal/templates/cronjob-backend-processes.yaml
add decline url configuration for invitation process
The backend needs the configuration to set the correct decline url for the invitation mail template
Refs: https://github.com/eclipse-tractusx/portal-backend/issues/701
https://github.com/eclipse-tractusx/portal-backend/pull/727
> fix(decline): add decline url for invite process

- charts/portal/templates/deployment-backend-administration.yaml
- charts/portal/templates/deployment-backend-appmarketplace.yaml
- charts/portal/templates/deployment-backend-notification.yaml
- charts/portal/templates/deployment-backend-registration.yaml
- charts/portal/templates/deployment-backend-services.yaml
- charts/portal/values.yaml
Parameter validateLifetime has been added to the configuration of backendservices to enable expiration-check of keycloak-tokens.
without this configuration the backendservices accept expired tokens from keycloak. This is a security-issue.
https://github.com/eclipse-tractusx/portal-backend/issues/586
N/A
> feat(keycloak): add parameter clockSkew to jwtBearerOptions

- charts/localdev/Chart.yaml
- charts/localdev/README.md
- charts/localdev/README.md.gotmpl
- charts/localdev/values.yaml
- chore(localdev): set valid encryption keys, addresses https://github.com/eclipse-tractusx/portal-backend/issues/787
- chore: use dim wallet
- docs: improve readme for tls disabled
- chore(localdev): bump chart version, remove appVersion
enable local development
> chore: improve localdev chart, especially for R24.05 configuration

- charts/portal/templates/job-backend-portal-migrations.yaml
- charts/portal/values.yaml
- enable seeding of test data with configmap
and move default seeding path and processidentity userid out of values file, into job, as changing those values isn't intuitive
https://github.com/eclipse-tractusx/tractus-x-umbrella/issues/105
> feat(portalmigrations): enable seeding of test data with configmap

- charts/portal/templates/cronjob-backend-processes.yaml
- charts/portal/values.yaml
- fix: add environment variable to use dim in application checklist bpdm
- docs: add install comment to useDimWallet value
https://github.com/eclipse-tractusx/portal/issues/361
> fix: add usedim wallet env var and improve docs

- CHANGELOG.md
- charts/portal/README.md
- charts/portal/values.yaml
Set correct path for consent osp
In portal and registration app the consent osp overlay has been moved to a page and the URL path changed.
[#907](https://github.com/eclipse-tractusx/portal-frontend/issues/907)
> fix: set correct path for consent osp

- charts/portal/values.yaml
For appmarketplace, changed approveAppUserRoles role1 to "App Manager".
Currently Service Manager receives notifications regarding app approval process. App Manager seems to be the appropriate user role to receive this notification.
Refs:  #370
> fix(roles): update role name for approval notifications in appmarketplace

- charts/portal/templates/deployment-backend-administration.yaml
- charts/portal/templates/deployment-backend-notification.yaml
Remove central-db-password dependency for administration and notification service. This was missed in: https://github.com/eclipse-tractusx/portal/pull/355
Administration and notification service still expected central-db-password as kubernetes secret.
Refs: #382
> fix(secrets): remove unused secret

- charts/portal/templates/deployment-backend-appmarketplace.yaml
Add wallet information settings to the marketplace service
Those values got introduced to be display as provider information
Refs: #841
https://github.com/eclipse-tractusx/portal-backend/pull/867
> fix: add config values for external service information

- charts/portal/templates/deployment-backend-administration.yaml
- charts/portal/templates/deployment-backend-appmarketplace.yaml
- charts/portal/templates/deployment-backend-notification.yaml
- charts/portal/templates/deployment-backend-registration.yaml
- charts/portal/templates/deployment-backend-services.yaml
- charts/portal/templates/deployment-frontend-assets.yaml
- charts/portal/templates/deployment-frontend-portal.yaml
- charts/portal/templates/deployment-frontend-registration.yaml
- charts/portal/values.yaml
This work has been done together with @gomezbc
The imagePullSecrets field allows you to specify secrets needed to pull Docker images from private repositories.
In many organizations, container images are stored in private registries rather than public ones for security and compliance reasons. To pull these images, Kubernetes needs credentials, which are provided via imagePullSecrets. This code dynamically includes the necessary secrets for pulling images, based on the configuration provided in the Helm chart's values file.
Would it be interesting to add this implementation to other tractus-x charts?
> feat: add imagePullScrets

- charts/portal/templates/deployment-backend-administration.yaml
Added config value for clearinghouseConnectDisabled to the registration settings in the administration service
The backend has added a check for the clearinghouseConnectDisabled in the registration business logic, therefor the value is needed in the configuration
Refs: https://github.com/eclipse-tractusx/portal-backend/issues/837
https://github.com/eclipse-tractusx/portal-backend/pull/847
> feat(sdFactory): add clearinghouseConnectDisabled to config

- charts/localdev/Chart.yaml
- charts/localdev/values.yaml
- reference portal chart over filesystem
- integrate changes from 2.1.0 portal version
https://github.com/eclipse-tractusx/portal/issues/399
> chore(localdev): reference portal chart from filesystem and integrate portal v2.1.0

- charts/localdev/README.md
- charts/localdev/README.md.gotmpl
- charts/localdev/values.yaml
- add className to portal ingresses
- add info about postgres subchart of portal which needs to be downloaded due to change to filesystem https://github.com/eclipse-tractusx/portal/pull/401
https://github.com/eclipse-tractusx/portal/issues/399
> chore(localdev): add ingress classname and improve docs

- charts/localdev/README.md
- charts/localdev/README.md.gotmpl
- charts/localdev/values.yaml
Documentation has been updated for windows with wsl2 and docker desktop integrated kubernetes
localdev doesn't run on Windows docker desktop integrated kubernetes
#399
> chore(localdev): add windows/wsl2 specific documentation

- charts/portal/templates/cronjob-backend-processes.yaml
Add config value for the self description documents
The config is needed for the backend
Refs: https://github.com/eclipse-tractusx/portal-backend/issues/813
https://github.com/eclipse-tractusx/portal-backend/pull/938
> fix: add config for sd document

- charts/portal/templates/deployment-backend-administration.yaml
Need to add authServiceUrl value for internal user type 
GET: api/administration/serviceaccount/owncompany/serviceaccounts/{GetServiceAccountId}
authServiceUrl added in portal administration service 
[#976](https://github.com/eclipse-tractusx/portal-backend/issues/976)
> feat(technicaluser): authServiceUrl value added in administration service

- charts/portal/templates/cronjob-backend-portal-maintenance.yaml
- charts/portal/templates/cronjob-backend-processes.yaml
- charts/portal/templates/job-backend-portal-migrations.yaml
- charts/portal/templates/job-backend-provisioning-migrations.yaml
- charts/portal/values.yaml
Enabled more imagepullsecrets to the previous portal PR [clipse-tractusx/portal/pull/396](https://github.com/eclipse-tractusx/portal/pull/396)
In many organizations, container images are stored in private registries rather than public ones for security and compliance reasons. To pull these images, Kubernetes needs credentials, which are provided via imagePullSecrets. This code dynamically includes the necessary secrets for pulling images, based on the configuration provided in the Helm chart's values file.
> feat: add imagePullSecrets

- environments/helm-values/values-int.yaml
adjust config for enabled startSharingStateAsReady from BPDM side
--> value not needed anymore in environment specific values file as it can default to true which is set in the values.yaml
Please include a summary of the change.
it was decided that the ready state should be managed from BPDM side
n/a
relates to https://github.com/eclipse-tractusx/portal-frontend/issues/1026 and https://github.com/eclipse-tractusx/portal-frontend/issues/955
> chore(int): adjust config for enabled startSharingStateAsReady

- charts/portal/templates/cronjob-backend-processes.yaml
- charts/portal/values.yaml
- environments/helm-values/values-int.yaml
adjusted the configuration for the dim middle layer to be configureable to use other idps than the central idp
To have the possibility to use another idp than the central idp for the dim middle layer
Refs: #373
> fix(dim): adjust dim configuration to enable other idps

- charts/localdev/README.md
Describe cntlm setup
Some corporate users are behind a firewall and have to setup internet access through http proxy.
https://github.com/eclipse-tractusx/portal/issues/399
> docs: describe cntlm setup

- CONTRIBUTING.md
Fix the "How to Contribute" link.
The existing link is broken.
[Issue #483](https://github.com/eclipse-tractusx/portal/issues/483) 
> docs: fix how to contribute link

- charts/localdev/Chart.yaml
- charts/localdev/values-tls.yaml
bump keycloak instances to v4.0.1
https://github.com/eclipse-tractusx/portal-iam/issues/254
> build(localdev): bump keycloak instances to v4.0.1

- .github/workflows/portal-chart-test.yaml
set set replicaCount=1 and postgresql.architecture=standalone
and update version to upgrade from
don't waste resources at helm install testing
https://github.com/eclipse-tractusx/portal-backend/issues/1262
> chore: improve resources for helm test

- environments/helm-values/values-int.yaml
Replace clearing house url and idp realm for tagus.
New URL and keycloak realm is required v2 clearing house.
Refs: eclipse-tractusx/sig-release#993
> chore(envs): tagus clearinghouse addresses

- charts/portal/templates/cronjob-backend-processes.yaml
- charts/portal/templates/deployment-backend-administration.yaml
sdfactoryIssuerBpn is removed from sdFactory-settings
with merge of PR https://github.com/eclipse-tractusx/portal-backend/pull/1290 this setting is obsolete.
https://github.com/eclipse-tractusx/portal-backend/issues/1288
Link to PR in other repository:
https://github.com/eclipse-tractusx/portal-backend/pull/1290
> chore(values): remove sdfactoryIssuerBpn

- charts/portal/templates/cronjob-backend-processes.yaml
- charts/portal/templates/deployment-backend-administration.yaml
Use configurable poolApiPath in BPDM pool address for application activation.
Hardcoded path in portal backend does not follow intended behavior if Pool address is using any additional pathing [other than v6](https://github.com/eclipse-tractusx/portal/blob/ef675d0db0eb29e1e54ad3a6ecda2daec1df126e/charts/portal/values.yaml#L51).
Refs: eclipse-tractusx/portal-backend#1299
> fix(registration): bpdm pool address for membership activation

- charts/portal/templates/cronjob-backend-processes.yaml
- charts/portal/templates/deployment-backend-administration.yaml
- charts/portal/values.yaml
Add configuration for expected error code from clearing house.
Error code sent by clearing house. Allows connector document creation to be skipped when receiving this error code.
Refs: eclipse-tractusx/portal-backend#1301
> feat: Add connectorAllowSdDocumentSkipErrorCode to backend configurations

- charts/portal/Chart.yaml
- charts/portal/templates/cronjob-backend-portal-maintenance.yaml
- charts/portal/templates/cronjob-backend-processes.yaml
For the imagePullSecrets in the cronjob type template, the indentation needs to be two more spaces due to the fact that it has "one more father" than the Deployments or Jobs templates.
> fix: fix Image Pull Secret Indentation for Cronjobs

- charts/portal/values.yaml
Increase memory requests and limit for administration service
- requests: 600M -> 650M
- limits: 600M -> 650M
Startup for administration service does not have enough memory.
https://github.com/eclipse-tractusx/portal/issues/541
> chore(memory): increase memory for administration service
